function [hmcConfounds] = motionQA(motionParams, spikeThreshold)
% Estimate and summarize head motion-related confounds.
%
% FORMAT [hmcConfounds] = motionQA(motionParams, spikeThreshold)
%
% REQUIRED INPUT:
%   motionParams
%       nTR x 6 matrix of head motion parameters, e.g., as contained in the
%       'rp' files generated by SPM during realignment. NB: the first three
%       columns of this matrix *must* correspond to translations
%       (displacements) in mm; the last three columns *must* correspond to
%       rotations in radians.
%
%   spikeThreshold
%       Amount of *total head motion* (in mm) required to qualify as a 
%       'motion spike' on any given TR. Defaults to 0.50 mm but you could
%       potentially be a bit more liberal (up to 1 mm).
%
% OUTPUT:
%   hmcConfounds
%       Structure array with the following fields:
%           .FD                - nTR x 1 vector of framewise diplacements.
%           .meanFD            - Mean framewise displacement.
%           .medFD             - Median framewise displacement.
%           .maxFD             - Max framewise displacement.
%           .spikeRegressors   - nTR x nSpike matrix of 'spike regressors',
%                                where each column is comprised of zeros in
%                                each row except for the TR on which a
%                                given motion spike occurred (defined by
%                                spikeThreshold).
%           .spikePercentage   - The percentage of frames showing total
%                                motion above spikeThreshold.
%           .motionRegressors  - nTR x 24 matrix of head motion regressors,
%                                including the original 6 motion
%                                parameters, an AR(1) realization, and the
%                                squares of each.
%__________________________________________________________________________
%
% Here we compute some basic QA measures with respect to head motion
% (namely, framewise displacement; FD). FD summarizes the total/absolute 
% amount of head motion observed between TRs. We can use this to identify
% problematic subjects/scans whose data are likely to be contaminated by
% excessive motion artifacts.
%__________________________________________________________________________

% Set a default spike threshold of 0.50 mm if not defined.
%--------------------------------------------------------------------------
if (nargin < 2)
    spikeThreshold = 0.50;
end

% Estimate framewise displacement.
%--------------------------------------------------------------------------   
% First convert rotations to displacements (in mm). Assuming rotations are
% in columns 4:6 and are given in radians, simply multiply by 50 (this is
% like taking an arc length along a sphere with radius = 50 mm, i.e., 
% assuming by convention that the average distance from the center of the 
% brain to the edge is ~50 mm).

% ZK (6/9/2025) - I used FSL to perform motion correction, so the first
% three columns correspond to rotation, and the last three correspond to
% translation. Adding code to format my motion parameters in a way that
% this script expects.
temp = zeros(size(motionParams));
temp(:,1:3) = motionParams(:,4:6);
temp(:,4:6) = motionParams(:,1:3);
motionParams = temp;

motionParams(:,4:6) = motionParams(:,4:6) .* 50;

% Backwards-differentiate to obtain motion relative to the previous TR.

dMP = diff(motionParams);

% Get total framewise displacement (FD) TR-to-TR by taking the sum of the 
% absolute values across differentiated motion parameters.

FD = sum(abs(dMP), 2);

% FD is a timeseries, so get some summary statistics: we'll take the mean,
% median (since FD is typically not normally-distributed), and max.

meanFD = mean(FD);
medFD  = median(FD);
maxFD  = max(FD);

% Append a zero to the beginning of the FD timeseries (assuming no relative
% motion on the first TR).

FD = [0; FD];

% Define motion spikes.
%--------------------------------------------------------------------------  
% Identify time points where FD exceeds spike threshold.

spikeID = find(FD >= spikeThreshold);

% Construct matrix of spike regressors (if necessary - it's possible there
% are no TRs with motion spikes). Each spike gets its own regressor, which
% is a binary vector with a 1 on the TR where the spike occurred and 0
% everywhere else.

if (~isempty(spikeID))

    spikeRegressors = zeros(size(FD,1), length(spikeID));

    for iSpike = 1:length(spikeID)

        spikeRegressors(spikeID(iSpike), iSpike) = 1;

    end

else

    spikeRegressors = [];

end 

% Get percentage of frames contaminated with motion spikes.
    
spikePercentage = length(spikeID) / length(FD) * 100;

% Construct more robust matrix of head motion regressors.
%--------------------------------------------------------------------------  
% Here we use a Volterra expansion of the 6 motion parameters, which may
% help account for instantaneous, time-lagged, and nonlinear effects of
% head motion on the BOLD signal.

X  = motionParams;
dx = [zeros(1,size(X,2)); X(1:end-1,:)];
X  = [X, dx, X.^2, dx.^2];

% Collect outputs.
%--------------------------------------------------------------------------  
hmcConfounds = struct('FD', FD, 'meanFD', meanFD, 'medFD', medFD, 'maxFD', maxFD, ...
                      'spikeRegressors', spikeRegressors, 'spikePercentage', spikePercentage, ...
                      'motionRegressors', X);

end